### ISSUE TITLE
Please make Functional App for example and clone.

### ISSUE THREAD

**Issue by wellington1993** [bhgames/zimbreasy#1]
@bhgames  Do you make me a favor?, I am recent start on Ruby Rails programming. On rails clean and new App, what is first stage to require and use this Gem, for example simple rails app to Create zimbra account. Thanks...

**Comment by bhgames** [comment]
Hey @welligton1993 I'd recommend checking out https://github.com/bhgames/em-zimbreasy, which is a more recent incarnation of this library. The README is pretty clear. What I would do, if I were you, is instantiate a new zimbreasy client in a Rails initializer:

in config/initializers/zimbreasy.rb:

ZIMBREASY_CLIENT = ...

Using the example in the README.

Then in your Rails actions and models, you can use ZIMBREASY_CLIENT as a global.

**Comment by wellington1993** [comment]
@bhgames  Thanks!!! I am go to try the em-zimbreasy...
